<!--东风金融-创格开单协议-->
<template>
 		<div>

			<p style="font-size:18pt; line-height:115%; margin:0pt 0pt 12pt; orphans:0; text-align:center; widows:0"><span style="font-family:微软雅黑; font-size:18pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:18pt">开单协议</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">开单人、原始持单人在平等自愿、友好协商的基础上，根据《中华人民共和国合同法》及相关法律规定，在认可并</span><span style="font-family:微软雅黑; font-size:12pt">签署《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的前提下，</span><span style="font-family:微软雅黑; font-size:12pt">达成《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单协议》，本协议在</span><span style="font-family:微软雅黑; font-size:12pt; text-decoration:underline">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; text-decoration:underline">平台</span><span style="font-family:微软雅黑; font-size:12pt">签署：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">一、定义</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台：</span><span style="font-family:微软雅黑; font-size:12pt">是专业的供应链科技服务平台</span><span style="font-family:微软雅黑; font-size:12pt">。本平台网站的运营权归</span><span style="font-family:微软雅黑; font-size:12pt">芜湖市</span><span style="font-family:微软雅黑; font-size:12pt">好用汽车租赁</span><span style="font-family:微软雅黑; font-size:12pt">有限公司所有。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">用户/会员：指在本平台完成注册，进行投融资信息发布，融资对接（包括但不限于企业方、资金方、</span><span style="font-family:微软雅黑; font-size:12pt">担保方、交易信息发布方</span><span style="font-family:微软雅黑; font-size:12pt">）等所有参与本平台活动并依法具备民事权利能力和民事行为能力的自然人、法人或者其他组织。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》：指已注册成为</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台用户，并选择在本平台开立和使用</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">功能时勾选、认可并签署的《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》以及不时被更新、替换、补充、修订的版本，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台发布的届时有效的各项业务规则、操作流程、通知通告、使用说明和指引等文件为本协议不可分割的部分，与本协议具有同等的法律效力。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台</span><span style="font-family:微软雅黑; font-size:12pt">为</span><span style="font-family:微软雅黑; font-size:12pt">用户</span><span style="font-family:微软雅黑; font-size:12pt">提供的一种可流转、可融资、可拆分、可兑付的电子付款承诺凭证</span><span style="font-family:微软雅黑; font-size:12pt">，开单人</span><span style="font-family:微软雅黑; font-size:12pt">承诺</span><span style="font-family:微软雅黑; font-size:12pt">到期支付货款</span><span style="font-family:微软雅黑; font-size:12pt">的</span><span style="font-family:微软雅黑; font-size:12pt">义务</span><span style="font-family:微软雅黑; font-size:12pt">，持单人可向资金方转让以获取对价</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">开单人：指根据本协议，在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台申请开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并负有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务的债务人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">持单人：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的持有人，根据本协议签收</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并享有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下到期款项债权的权利人。持单人包括原始持单人以及其他根据本协议受让</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台认证用户。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">原始持单人：指根据本协议，在本平台确认签收开单人开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的用户，为基础合同的卖方或服务提供方，也是</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的第一手持有人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">基础交易：</span><span style="font-family:微软雅黑; font-size:12pt">指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">对应的原始持单人和开单人之间因销售商品、提供服务或其他贸易活动产生的债权债务关系（涉及人力成本支出等费用的除外）</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">基础合同：</span><span style="font-family:微软雅黑; font-size:12pt">指由原始持单人与开单人基于基础交易而签订的货物销售合同、服务合同或其他交易文件，亦包括其补充协议和构成销售/服务合同组成的附件，但因涉及人力成本支出等费用签订的相关文件除外</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">资金方：指根据法律法规及本协议约定，在受让本平台认证用户的应收账款（含</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">）的基础上，提供融资服务，包括但不限于商业资金方、银行机构。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">核心企业：指已完成平台注册的在产业链中被公认的优势企业。该企业为了巩固其产业链发展，优化产业、提升产业的竞争力等，</span><span style="font-family:微软雅黑; font-size:12pt">组织其上下游企业建设供应链金融体系，提供更加优质便捷的供应链金融服务</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">日：指根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载信息，开单人履行</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务，持单人获取</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付款项的日期。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">担保人：为</span><span style="font-family:微软雅黑; font-size:12pt">开单人</span><span style="font-family:微软雅黑; font-size:12pt">开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下</span><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">义务提供担保，承担连带付款责任的自然人、法人或其他组织。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">开单额度：指资金方评估</span><span style="font-family:微软雅黑; font-size:12pt">开单人</span><span style="font-family:微软雅黑; font-size:12pt">的资信状况，为</span><span style="font-family:微软雅黑; font-size:12pt">开单人</span><span style="font-family:微软雅黑; font-size:12pt">核定的开单最大限额、并进行开单额度动态管理，该额度在有效期内可循环使用。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">担保额度：指担保人为</span><span style="font-family:微软雅黑; font-size:12pt">开单人</span><span style="font-family:微软雅黑; font-size:12pt">核定的，对其开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">承担连带付款责任（还款保证责任）的最大限额，该额度在有效期内可循环使用。</span></li>
			</ol>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">二、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">开单概述</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">开单人根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的业务规则和指引申请开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">，申请开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">为载有一定金额的、作为基础合同的应收账款电子付款债务凭证，并</span><span style="font-family:微软雅黑; font-size:12pt">承诺</span><span style="font-family:微软雅黑; font-size:12pt">在一定的期限内凭</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">兑付，开单人作为应收账款债务人，持单人作为应收账款债权人。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开立成功，开单人作为负有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务的债务人，持单人作为享有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下到期款项的权利人。成功开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">，可作为本平台其他服务的交易基础和承诺支付凭证。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">提请注意：仅有</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">平台认证用户适用于</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">开单服务</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">三、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">开单流程</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单申请</span><span style="font-family:微软雅黑; font-size:12pt">及审核</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.1开单人提出</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单申请的，应通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台，根据《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的</span><span style="font-family:微软雅黑; font-size:12pt">规则</span><span style="font-family:微软雅黑; font-size:12pt">，填写完毕</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单申请资料，上传完毕全部</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单申请文件，并勾选本协议。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1</span><span style="font-family:微软雅黑; font-size:12pt">.2</span><span style="font-family:微软雅黑; font-size:12pt">开单人勾选本协议，视为同意本协议全部内容。开单人承诺保证按照</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">所载内容履行付款义务，并愿意承担逾期付款的违约责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1</span><span style="font-family:微软雅黑; font-size:12pt">.3</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单后，须由开单人审核通过</span><span style="font-family:微软雅黑; font-size:12pt">后，流转至</span><span style="font-family:微软雅黑; font-size:12pt">原始</span><span style="font-family:微软雅黑; font-size:12pt">持单人</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.4</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单后，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台自动生成</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单记录，双方可通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">查询功能进行查询，该记录为本协议的组成部分。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单签收</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2.1</span><span style="font-family:微软雅黑; font-size:12pt">持单人收到开单人</span><span style="font-family:微软雅黑; font-size:12pt">开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">后，应通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台，根据</span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的规则</span><span style="font-family:微软雅黑; font-size:12pt">，</span><span style="font-family:微软雅黑; font-size:12pt">对开单人开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">签收“同意”或“拒绝”。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">.</span><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">签收后，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台自动生成</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单</span><span style="font-family:微软雅黑; font-size:12pt">及</span><span style="font-family:微软雅黑; font-size:12pt">签收记录，双方可通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">查询功能进行查询。该记录为本协议的组成部分，</span><span style="font-family:微软雅黑; font-size:12pt">与本协议具有同等法律效力</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">开单</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">业务</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">，开单人及原始持单人均勾选了本协议，视为双方同意本协议的条款</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">四、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">的使用</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、使用</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">，须注册为平台的会员且会员只能在平台上使用</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的开单人、持单人均同意</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">及其对应债权可以转让，并认可持单人可将其持有的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">拆分使用。拆分后的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">金额之和等于拆分前的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">金额。</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的流转使用不限次数，各次流转分别独立、不可追索。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">可以作为到期付款承诺使用，开单人应基于真实的贸易背景，将其所开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让给其债权人即原始持单人，作为原始持单人到期要求开单人付款的凭证。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、原始持单人/持单人可以将持有的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">全部或部分通过平台转让给其他平台用户，平台通过系统消息向持单人对应的直接债务人（即开单人）发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》，该通知到达持单人对应的直接债务人在平台的账户即视为债权转让通知已经送达。但是，在平台限定的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">到期前的一定期限内，持单人须持有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">到期，等待开单人的资金偿付。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">5、持单人可以向资金方申请融资，具体手续依照平台相关业务规则所规定的流程办理。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">如果</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">向持单人提供保理融资，则</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">亦可向银行申请再保理融资。银行受理持单人或</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">的融资时，银行将作为</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">最终持单人，委托平台通过系统消息向持单人对应的直接债务人（即开单人）发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》，该通知到达持单人对应的直接债务人在平台的账户即视为债权转让通知已经送达。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">6、持单人可以持有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">直至到期兑付。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">7、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">平台无责任或义务将</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">兑换为任意额度现金或有价证券，亦不为</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">承担任何形式的担保或偿还责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">五、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">的管理及到期支付</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台提供</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">管理服务，具体包括：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）记录每一笔</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的使用情况；</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）向开单人提供最终还款明细表查询服务；</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（3）向开单人发出付款到期提醒；</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（4）向会员提供电子法律文本的备份、查看、核对、下载服务；</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（5）</span><span style="font-family:微软雅黑; font-size:12pt">受持单人委托通过系统消息/邮件/短信等任一种方式向开单人发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、平台系统所记录的数据和信息是确定交易具体内容的依据，各方对此予以确认并不持异议。负责填写的各方承诺并确保其数据和信息完全真实合法，不存在虚假、隐瞒信息的情形。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、</span><span style="font-family:微软雅黑; font-size:12pt">开单人应在承诺付款日之前将相等于承诺付款金额的资金转入</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">还款账户，并在此不可撤销地授权</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">，由</span><span style="font-family:微软雅黑; font-size:12pt">资金方</span><span style="font-family:微软雅黑; font-size:12pt">将转入还款账户的资金向持单人支付。由于银行</span><span style="font-family:微软雅黑; font-size:12pt">系统结算等原因，持单人实际收到款项的时间可能会晚于承诺付款日。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、商务合同项下的纠纷不影响</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">与</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">流转的效力，开单人仍须按照到期付款承诺函的约定偿还款项，持单人不得要求将已流转的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">退还给开单人或前手持单人，如需就商务合同进行退款、赔偿等，由相关方另行协商解决。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">5、如果开单人未按照到期付款承诺函约定的日期偿还款项，应承担相应的违约责任，具体详见《付款承诺书》。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">六、承诺与保证</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议开单人、原始持单人相互承诺和保证如下：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.1</span><span style="font-family:微软雅黑; font-size:12pt">双方均为</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台认证用户，双方承诺遵守《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》。双方各自在《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》项下的陈述和保证为本协议的一部分，其一旦违反将需承担《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》和本协议项下的违约责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.2</span><span style="font-family:微软雅黑; font-size:12pt">&#xa0;</span><span style="font-family:微软雅黑; font-size:12pt">双方各自具有签署本协议和履行本协议所规定各项义务的完整的合法资格，并取得了签署和履行本协议的所有内部授权及批准，本协议经签署后对双方是合法、有效、有约束力并可强制执行的。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.3</span><span style="font-family:微软雅黑; font-size:12pt">双方签署和履行本协议并不违反其所适用的任何法律、法规、规范性文件或政府机构的许可或批准，亦不违反任何对其有约束力的组织文件或其与任何第三方签订的任何合同或协议（或者已取得第三方的同意或认可）。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1.4双方承诺，开立和签收的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">有真实的贸易背景，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下基础交易所对应的基础合同已妥善签署、合法、有效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、开单人承诺</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2.1开单人承诺作为应收账款的债务人，因其与原始持单人在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下的基础交易而依法或根据合同约定取得的任何抗辩权，不得用于对抗资金方以及因</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让而持有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的任意</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台用户。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2.2开单人承诺在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">载明的</span><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">日期按时足额向持单人支付款项赎回</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2.3开单人在开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">前/时及以后，不曾亦保证不会就</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下应收账款的全部或任何部分，通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台重复开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">给第三方或通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台外的途径转让或质押给任何第三方。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2.4开单人承诺、保证并同意</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让后，原始持单人对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">享有完全的权利，包括但不限于到期收到本金、利息权益、违约金权益、损害赔偿权益、担保权益以及再转让权等。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">七、税费</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">持单人、开单人和资金方按照中国法律、行政法规、规章的规定承担各自因履行本协议而产生的相应税负，或承担履行代扣代缴义务。持单人和开单人因履行本协议过程中所产生的税负，除非本协议另有约定，应由原始持单人和开单人依法各自承担。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">八、保密</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">为保证本协议的全面履行，双方承诺就对方提供的所有资料中所包含的商业秘密和非公开信息严格保密，未经对方同意不得向第三方披露。无论本协议是否终止或解除，本条款在保密期限内持续有效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">九、违约责任</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、开单人违反</span><span style="font-family:微软雅黑; font-size:12pt">本协议</span><span style="font-family:微软雅黑; font-size:12pt">第六条“承诺和保证”中的任一事项，或违反本协议其他约定义务的事项的，构成开单人</span><span style="font-family:微软雅黑; font-size:12pt">违约</span><span style="font-family:微软雅黑; font-size:12pt">，已支付的平台费用不予退还，并承担由此给平台造成的一切损失。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、原始</span><span style="font-family:微软雅黑; font-size:12pt">持单人</span><span style="font-family:微软雅黑; font-size:12pt">违反</span><span style="font-family:微软雅黑; font-size:12pt">本协议</span><span style="font-family:微软雅黑; font-size:12pt">第六条“承诺和保证”中的任一事项，或违反本协议其他约定义务的事项的，构成原始</span><span style="font-family:微软雅黑; font-size:12pt">持单人违约</span><span style="font-family:微软雅黑; font-size:12pt">，已支付的平台费用不予退还，并承担由此给平台造成的一切损失。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、一方违反本协议约定的，守约方有权要求违约方承担根据法律、法规的规定承担违约责任的权利，但该其他违约责任的承担将与本条的约定相抵触的情况除外。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">十、适用法律及争议的解决</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议的订立、效力、解释、执行以及争议解决均适用中华人民共和国法律。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、因本协议引起的或与本协议有关的任何争议，应尽最大诚意进行友好协商，</span><span style="font-family:微软雅黑; font-size:12pt">三</span><span style="font-family:微软雅黑; font-size:12pt">十（</span><span style="font-family:微软雅黑; font-size:12pt">3</span><span style="font-family:微软雅黑; font-size:12pt">0）日内协商不成的，任何一方均有权将该争议向</span><span style="font-family:微软雅黑; font-size:12pt">芜湖</span><span style="font-family:微软雅黑; font-size:12pt">市</span><span style="font-family:微软雅黑; font-size:12pt">经开</span><span style="font-family:微软雅黑; font-size:12pt">区人民法院提起诉讼。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、当产生任何争议及任何争议正按前条规定进行解决时，除争议事项外，双方应继续行使本协议项下的其他权利，履行本协议项下的其他义务。如本协议中的任何条款被认定为全部或部分不合法、无效或不可强制执行，并不影响其他条款的有效和执行。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">十一、其他</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议自原始持单人根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的规则对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开立进行签收同意之日起成立并生效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、本协议未尽之事宜，如《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》已有约定的，适用《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的约定。如《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》没有约定的，由双方另行协商并签订补充协议解决，另行签订的补充协议与本协议具有同等法律效力。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、双方应秉承诚实信用之原则，采取一切必要的行为以确保本协议之生效及获完全执行，并避免采取任何与本协议条款不一致的行为。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、除非本协议另有约定，本协议生效后，任何一方不得单方面变更或解除本协议；对本协议的任何修改或变更必须经协议各方协商一致，并达成书面协议。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">5、本协议及其修改或补充均采用通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台以电子文本形式制成，可以有一份或者多份并且每一份具有同等法律效力，并保存在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台为此设立的专用服务器上备查和保管。双方均认可该形式的协议效力。</span><span style="color:#222222; font-family:等线; font-size:10.5pt">&#xa0;</span></p>
		</div>
</template>
