<!--融资服务指引-->
<template>
	<div>
			<p style="margin:7.8pt 0pt; text-align:center"><span style="font-family:微软雅黑; font-size:18pt; font-weight:bold">融资服务</span><span style="font-family:微软雅黑; font-size:18pt; font-weight:bold">协议</span></p>
			<p style="margin:7.8pt 0pt; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">本平台向融资申请人提供线上供应链融资服务。合作期间，融资申请人通过本平台提交融资申请，在线完成全部或者部分融资业务流程。为加强合作关系，提升业务办理效率，根据《中华人民共和国合同法》、《中华人民共和国物权法》、《中华人民共和国电子签名法》及有关法律规定，订立本指引，以资各方信守。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">一、定义</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台：是专业的</span><span style="font-family:微软雅黑; font-size:12pt">供应链</span><span style="font-family:微软雅黑; font-size:12pt">金融</span><span style="font-family:微软雅黑; font-size:12pt">服务平台</span><span style="font-family:微软雅黑; font-size:12pt">。本平台网站的运营权归</span><span style="font-family:微软雅黑; font-size:12pt">芜湖市好用汽车租赁</span><span style="font-family:微软雅黑; font-size:12pt">有限公司所有。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格平台</span><span style="font-family:微软雅黑; font-size:12pt">为</span><span style="font-family:微软雅黑; font-size:12pt">用户</span><span style="font-family:微软雅黑; font-size:12pt">提供的一种可流转、可融资、可拆分、可兑付的电子付款承诺凭证</span><span style="font-family:微软雅黑; font-size:12pt">，开单人承诺到期支付货款的义务，持单人可向资金方转让以获取对价</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">无追索权供应链融资：是指融资申请人通过本平台向资金方转让其持有的以</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">为凭证的应收账款，并发起融资申请，资金方为融资申请人提供的无追索权供应链融资服务。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">融资申请人：指向资金方转让其对开单人享有的、以</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">为凭证的应收账款债权并向资金方申请供应链融资的持单人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">开单人：指根据本协议，在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台申请开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并负有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务的债务人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">持单人：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的持有人，根据本协议签收</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并享有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下到期款项债权的权利人。持单人包括原始持单人以及其他根据本协议受让</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台认证用户。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">原始持单人：指根据本协议，在本平台确认签收开单人开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的用户，为基础合同的卖方或服务提供方，也是</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的第一手持有人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">资金方：指根据法律法规及本协议约定，在受让本平台认证用户的应收账款（含</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">）的基础上，提供融资服务，包括但不限于商业资金方、银行机构。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">核心企业：指已完成平台注册的在产业链中被公认的优势企业。该企业为了巩固其产业链发展，优化产业、提升产业的竞争力等，组织其上下游企业建设供应链金融体系，提供更加优质便捷的供应链金融服务。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">日：指根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载信息，开单人履行</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务，持单人获取</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付款项的日期。</span></li>
			</ol>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">二、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">融资指引概述</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、融资申请人申请办理无追索权供应链融资时，通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台向资金方发送融资申请信息并提供资金方要求的相关资料，平台负责对融资申请人提供资料的完整性、有效性等进行初步形式审查，审核通过后将融资申请人提交的相关信息及资料推送给资金方进行实质审核，资金方最终决定是否同意融资申请，即</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资行为。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、为避免歧义，融资申请人在此确认，</span>
				<a name="_Hlk15586248"><span style="font-family:微软雅黑; font-size:12pt">本次</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资仅涉及融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">对应基础合同项下的应收货款权利，其他权利与义务仍由基础合同的当事人继续履行和承担。</span></a>
			</p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">三、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">融资流程</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资前提</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）融资申请应具备真实的贸易背景；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）于</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">兑付日3个工作日前提出融资申请；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（3）</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资金额应根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载的金额确定，不得高于</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载的金额；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（4）融资申请人勾选本指引，即视为已知悉并同意本指引全部内容；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（5）融资申请人应当向平台支付平台服务费，具体约定以后续相关方签订的相关协议为准。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资申请、平台服务费缴纳</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）融资申请人向资金方提出</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资申请的，应通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台，如实填写</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资申请信息（下称“融资资料”），并上传融资资料。融资资料包括但不限于：</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">①融资申请书；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">②营业执照正/副本复印件；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">③合同、发票、物流单据等；</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">④其他资料。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（</span><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">）融资申请之日至融资申请结束之日期间，融资申请人所持有的用作融资转让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">（下称“融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">”）将被限制转让，平台将视融资成败情况解除限制。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、平台形式审查</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）融资申请人按《平台收费服务协议》向平台支付本次融资申请所需的平台服务费，平台收到平台服务费后，对融资申请人上传平台的融资资料进行初步形式审查，审查时间不超过【2】个工作日。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">上述形式审查是指：融资申请人保证融资资料的真实性、完整性、合法性以及有效性，并保证其与上游供应商交易的真实合法，在此基础上本平台仅对资料进行表面的和形式上的审查；但是，经过形式审查未提出异议均不视为对任何权利的放弃，本平台保留在形式审查期间及在其后的任何时点，就融资申请人违反本平台融资规定的行为而按本指引的约定要求融资申请人承担责任的权利。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）平台形式审核完毕后，通过系统消息通知融资申请人“是否同意推送至资金方”：</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">a</span><span style="font-family:微软雅黑; font-size:12pt">、融资申请人通过平台形式审查的，平台在【1】工作日内通过系统消息通知融资申请人，并将融资资料推送至资金方进行实质审查。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">b</span><span style="font-family:微软雅黑; font-size:12pt">、融资申请人未通过平台形式审查的，平台在【1】工作日通过系统消息告知未通过原因，平台恢复</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">持有状态。融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">可按照平台的相关规则进行兑付、转让，并可根据退回原因补正后重新发起融资。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、资金方实质审查</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）</span><span style="font-family:微软雅黑; font-size:12pt">融资申请人通过平台形式审查后，平台将融资申请人的融资资料推送至资金方，由</span><span style="font-family:微软雅黑; font-size:12pt">资金方对融资申请人的融资申请进行实质审核。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）资金方实质审核完毕后，通过系统消息通知融资申请人与平台“是否同意融资申请”：</span><span style="color:#ff0000; font-family:微软雅黑; font-size:12pt"> </span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">a、若资金方同意融资申请，资金方应当通过系统消息及书面形式通知融资申请人与本平台。由</span><span style="font-family:微软雅黑; font-size:12pt">融资申请人与资金方双方签署线下融资协议，并于签订当日上传平台备案</span><span style="font-family:微软雅黑; font-size:12pt">。融资申请人与资金方应当根据本平台</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让规则完成融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让手续，具体手续依照平台相关业务规则所规定的业务流程为准。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让手续完成时，本次融资申请视为成功并结束。资金方将作为融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">最终持单人，委托平台通过系统消息向融资申请人对应的直接债务人（即开单人）发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》，该通知到达开单人在平台的账户即视为债权转让通知已经送达。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">b、若资金方拒绝融资申请，资金方应当通过系统消息通知融资申请人与本平台，本次融资申请视为失败并结束，平台恢复</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">持有状态。融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">可按照平台的相关规则进行兑付、转让、融资。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">5、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">融资申请完成后，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">查询功能进行查询。该等记录为本指引的组成部分，与本指引具有同等法律效力。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">6、</span><span style="font-family:微软雅黑; font-size:12pt">平台服务费的退回</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">若融资申请失败的，融资申请结束之日</span><span style="font-family:微软雅黑; font-size:12pt">5</span><span style="font-family:微软雅黑; font-size:12pt">个工作日内，平台需全额无息退还平台服务费。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">四、承诺与保证</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、融资申请人承诺所转让的融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">不存在任何瑕疵，也不存在资金方行使权利的限制，融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权真实、合法、有效；融资申请人未对债权设立质押或其他任何优先权益，且未曾向他人转让。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、融资申请人承诺所转让的融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权未曾与债务人有约定抵销、禁止或限制向资金方转让等事宜。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3</span><span style="font-family:微软雅黑; font-size:12pt">、除本指引的转让外，融资申请人不曾亦保证不会就融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下应收账款的全部或任何部分，通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台以外的途径转让或质押给任何第三方。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、融资申请人承诺、保证并同意融资</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让后，资金方对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">享有完全的权利，包括但不限于到期收到本金、利息权益、违约金权益、损害赔偿权益、担保权益以及再转让权等。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">五、税费</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">融资申请人、本平台按照中国法律、行政法规、规章的规定承担各自因履行本指引而产生的相应税负，或承担履行代扣代缴义务。因履行本指引过程中所产生的税负，除非本指引另有约定，依法各自承担。 </span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">六、保密</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">为保证本指引的全面履行，双方承诺就对方提供的所有资料中所包含的商业秘密和非公开信息严格保密，未经对方同意不得向第三方披露。无论本指引是否终止或解除，本条款在保密期限内持续有效。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">七、违约责任</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、融资申请人违反本指引第四条“承诺和保证”中的任一事项，或违反本指引其他约定义务的事项的构成违约，已支付的平台服务费不予退还，并承担由此给平台造成的一切损失。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">、一方违反本指引约定的，守约方有权要求违约方承担根据法律、法规的规定承担违约责任的权利，但其他违约责任的承担与本条约定的相抵触的情况除外。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">八、特别提示</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">1</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">本平台</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">拥有对本指引条款的修改权、更新权、解释权。本指引及其修改或补充均采用通过</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">平台以电子文本形式制成，并保存在</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">平台为此设立的专用服务器上备查和保管，每一份均是本指引不可分割的部分具有同等法律效力。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">2</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">、各方应秉承诚实信用之原则，采取一切必要的行为以确保本指引获完全执行，并避免采取任何与本指引条款不一致的行为。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">3</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">、各方理解并同意本平台已对</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">融资涉及的事项进行了充分的说明和提示，融资方与资金方有义务对</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">融资进行风险审核与把控（包括但不限于信息及交易的真实、合法、准确、风险等），自行判断分析后选择本指引提供的服务，并完全知悉平台无义务保证各方在提出</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">融资后能够实际达成交易的风险。</span></p>
			<p style="margin:7.8pt 0pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">&#xa0;</span></p>
		</div>
</template>
