<!--东风金融-创格转让协议-->
<template>
	<div>
			<p style="font-size:18pt; line-height:115%; margin:0pt 0pt 12pt; orphans:0; text-align:center; widows:0"><span style="font-family:微软雅黑; font-size:18pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:18pt">平台</span><span style="font-family:微软雅黑; font-size:18pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:18pt">转让协议</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">持单人与受让方在平等自愿、友好协商的基础上，根据《中华人民共和国合同法》及相关法律规定，在</span><span style="font-family:微软雅黑; font-size:12pt">认可并签署</span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》</span><span style="font-family:微软雅黑; font-size:12pt">和</span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">开单协议》前提</span><span style="font-family:微软雅黑; font-size:12pt">下，</span><span style="font-family:微软雅黑; font-size:12pt">达成《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让协议》，本协议在</span><span style="font-family:微软雅黑; font-size:12pt; text-decoration:underline">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; text-decoration:underline">平台</span><span style="font-family:微软雅黑; font-size:12pt">签署：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">一、定义</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台：是专业的供应链科技服务平台。本平台网站的运营权归</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">供应链科技有限公司所有。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">用户/会员：指在本平台完成注册，进行投融资信息发布，融资对接（包括但不限于企业方、资金方、交易信息的发布者）等所有参与本平台活动并依法具备民事权利能力和民事行为能力的自然人、法人或者其他组织。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》：指已注册成为</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台用户，并选择在本平台开立和使用</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">功能时勾选、认可并签署的《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》以及不时被更新、替换、补充、修订的版本，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台发布的届时有效的各项业务规则、操作流程、通知通告、使用说明和指引等文件为本协议不可分割的部分，与本协议具有同等的法律效力。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格平台</span><span style="font-family:微软雅黑; font-size:12pt">为</span><span style="font-family:微软雅黑; font-size:12pt">用户</span><span style="font-family:微软雅黑; font-size:12pt">提供的一种可流转、可融资、可拆分、可兑付的电子付款承诺凭证</span><span style="font-family:微软雅黑; font-size:12pt">，开单人承诺到期支付货款的义务，持单人可向资金方转让以获取对价</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">开单人：指根据本协议，在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台申请开立</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并负有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务的债务人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">持单人：指</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的持有人，根据本协议签收</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">并享有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下到期款项债权的权利人。持单人包括原始持单人以及其他根据本协议受让</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台认证用户。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">原始持单人：指根据本协议，在本平台确认签收开单人开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的用户，为基础合同的卖方或服务提供方，也是</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的第一手持有人。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">基础交易：</span><span style="font-family:微软雅黑; font-size:12pt">指东风金融-创格对应的原始持单人和开单人之间因销售商品、提供服务或其他贸易活动产生的债权债务关系（涉及人力成本支出等费用的除外）</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font:7.0pt 'Times New Roman'">&#xa0; </span><span style="font-family:微软雅黑; font-size:12pt">基础合同：</span><span style="font-family:微软雅黑; font-size:12pt">指由原始持单人与开单人基于基础交易而签订的货物销售合同、服务合同或其他交易文件，亦包括其补充协议和构成销售/服务合同组成的附件，但因涉及人力成本支出等费用签订的相关文件除外</span><span style="font-family:微软雅黑; font-size:12pt">。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">资金方：指根据法律法规及本协议约定，在受让本平台认证用户的应收账款（含</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">）的基础上，提供融资服务，包括但不限于商业资金方、银行机构。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">核心企业：指已完成平台注册的在产业链中被公认的优势企业。该企业为了巩固其产业链发展，优化产业、提升产业的竞争力等，组织其上下游企业建设供应链金融体系，提供更加优质便捷的供应链金融服务。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">日：指根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载信息，开单人履行</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付义务，持单人获取</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">偿付款项的日期。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">担保人：为开单人开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下</span><span style="font-family:微软雅黑; font-size:12pt">兑付</span><span style="font-family:微软雅黑; font-size:12pt">义务提供担保，承担连带付款责任的自然人、法人或其他组织。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">开单额度：指资金方评估开单人的资信状况，为开单人核定的开单最大限额、并进行开单额度动态管理，该额度在有效期内可循环使用。</span></li>
				<li style="font-family:微软雅黑; font-size:12pt; list-style-position:inside; margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">担保额度：指担保人为开单人核定的，对其开立的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">承担连带付款责任（还款保证责任）的最大限额，该额度在有效期内可循环使用。</span></li>
			</ol>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">二、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">转让概述</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt">
				<a name="_Ref419399897"><span style="font-family:微软雅黑; font-size:12pt">1、按照本协议规定的条件和条款，持单人可以将持有的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">全部或部分通过平台转让给其债权人（下称“受让方”），即</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让行为。</span></a>
			</p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、为避免歧义，持单人和受让方在此确认，</span>
				<a name="_Hlk15586248"><span style="font-family:微软雅黑; font-size:12pt">本次</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让仅涉及</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">对应基础合同项下的应收货款权利，其他权利与义务仍由基础合同的当事人继续履行和承担。</span></a>
			</p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">三、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">转让流程</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让前提</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的转让应具备真实的贸易背景；</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让金额应根据</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载的金额确定，不得高于</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">记载的金额。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让申请</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）持单人提出</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让申请的，应通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台，根据《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的规则，填写完毕</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让申请资料，上传完毕全部</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让申请文件，并勾选本协议。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）持单人勾选本协议，视为持单人同意本协议全部内容。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（3）</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让后，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台自动生成</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让记录，持单人可通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">查询功能进行查询。该等记录为本协议的组成部分，</span><span style="font-family:微软雅黑; font-size:12pt">与本协议具有同等法律效力</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的受让</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、受让方收到持单人</span><span style="font-family:微软雅黑; font-size:12pt">转让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">后</span><span style="font-family:微软雅黑; font-size:12pt">，应通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台，根据《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的规则，对受让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">进行签收，并点击“同意”或“拒绝”。若点击“同意”，则</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">受让完成。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">受让完成后，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台自动生成</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">受让记录，受让方可通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">查询功能进行查询。该等记录为本协议的组成部分，与本协议具有同等法律效力。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">本平台通过系统消息/邮件/短信等任一种方式向</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的开单人发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》，该通知到达</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的开单人在平台的账户即视为债权转让通知已经送达。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让</span><span style="font-family:微软雅黑; font-size:12pt">业务</span><span style="font-family:微软雅黑; font-size:12pt">，</span><span style="font-family:微软雅黑; font-size:12pt">持单人</span><span style="font-family:微软雅黑; font-size:12pt">及</span><span style="font-family:微软雅黑; font-size:12pt">受让方</span><span style="font-family:微软雅黑; font-size:12pt">均勾选了本协议，视为双方同意本协议的条款</span><span style="font-family:微软雅黑; font-size:12pt">。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">四、转让结果</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、受让方为持单人的供应商，双方已签署了关于购买货物或服务的基础合同，根据该等合同，持单人对受让方负有一定金额的债务。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">可作为到期付款承诺使用，到期受让方可要求开单人付款，受让方与持单人的债权债务关系在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让完成并兑付完毕后消灭。若存在兑付失败，则各方可基于其签订的交易协议追究相对方的法律责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">五、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">的使用与管理</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1</span><span style="font-family:微软雅黑; font-size:12pt">、受让方可以将受让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">全部或部分通过平台再次转让给其债权人，平台通过系统消息向</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的开单人发送《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让通知》，该通知到达开单人在平台的账户即视为债权转让通知已经送达。但是，在平台限定的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">到期前的一定期限内，持单人须持有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">到期，等待开单人的资金偿付。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">、受让方可以向保理公司或银行申请保理融资，具体手续依照平台相关业务规则所规定的流程办理。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3</span><span style="font-family:微软雅黑; font-size:12pt">、受让方可以持有</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">直至到期兑付。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">4</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">、</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">平台无责任或义务将</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">兑换为任意额度现金或有价证券，亦不为</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">承担任何形式的担保或偿还责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">六、承诺与保证</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议持单人、受让方双方在此相互承诺和保证如下：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）双方均为</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台认证用户，双方承诺遵守《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》。双方各自在《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》项下的陈述和保证为本协议的一部分，其一旦违反将需承担《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》和本协议项下的违约责任。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）双方各自具有签署本协议和履行本协议所规定各项义务的完整的合法资格，并取得了签署和履行本协议的所有内部授权及批准，本协议经签署后对双方是合法、有效、有约束力并可强制执行的。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（3）双方签署和履行本协议并不违反其所适用的任何法律、法规、规范性文件或政府机构的许可或批准，亦不违反任何对其有约束力的组织文件或其与任何第三方签订的任何合同或协议（或者已取得第三方的同意或认可）。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（4）双方承诺，开立和签收的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">有真实的贸易背景，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下基础交易所对应的基础合同已妥善签署、合法、有效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、持单人承诺：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（1）持单人承诺所转让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">不存在任何瑕疵，也不存在受让方行使权利的限制，</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权真实、合法、有效；持单人未对债权设立抵押、质押或其他任何优先权益，且未曾向他人转让。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（2）持单人承诺所转让的</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权未曾与债务人有约定抵销、禁止或限制向受让方转让等事宜；在受让方签收</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">后，持单人、开单人、受让方不得对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权的任何内容做出变更、终止、宽延或放弃。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（3）除本协议的转让外，持单人不曾亦保证不会就</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下应收账款的全部或任何部分，通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台以外的途径转让</span><span style="font-family:微软雅黑; font-size:12pt">、抵押</span><span style="font-family:微软雅黑; font-size:12pt">或质押给任何第三方。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">（4）持单人承诺、保证并同意</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让后，受让方对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">享有完全的权利，包括但不限于到期收到本金、利息权益、违约金权益、损害赔偿权益、担保权益以及再转让权等。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、受让方承诺：</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">受让方知悉</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">的转让为无追索权转让，如</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">到期未能得到偿付，或出现</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下基础交易所对应的基础合同有关的任何纠纷，受让方对持单人或其前手持单人（如有）不具有追索权，持单人亦无义务对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">项下债权的实现提供任何保证。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">七、税费</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">受让方、持单人和保理商按照中国法律、行政法规、规章的规定承担各自因履行本协议而产生的相应税负，或承担履行代扣代缴义务。受让方和持单人因履行本协议过程中所产生的税负，除非本协议另有约定，应由受让方和持单人依法各自承担。</span><span style="font-family:微软雅黑; font-size:12pt">&#xa0;</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">八、保密</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">为保证本协议的全面履行，双方承诺就对方提供的所有资料中所包含的商业秘密和非公开信息严格保密，未经对方同意不得向第三方披露。无论本协议是否终止或解除，本条款在保密期限内持续有效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">九、违约责任</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、持单人违反本协议第六条“承诺和保证”中的任一事项，或违反本协议其他约定义务的事项的，构成持单人违约，已支付的平台费用不予退还，并承担由此给平台造成的一切损失。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2</span><span style="font-family:微软雅黑; font-size:12pt">、一方违反本协议约定的，守约方有权要求违约方承担根据法律、法规的规定承担违约责任的权利，但该其他违约责任的承担将与本条的约定相抵触的情况除外。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt">
				<a name="_Hlk16090149"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">十、适用法律及争议的解决</span></a>
			</p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议的订立、效力、解释、执行以及争议解决均适用中华人民共和国法律。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、凡</span><span style="font-family:微软雅黑; font-size:12pt">因本协议引起的或与本协议有关的任何争议，应首先由双方协商解决，三</span><span style="font-family:微软雅黑; font-size:12pt">十（</span><span style="font-family:微软雅黑; font-size:12pt">3</span><span style="font-family:微软雅黑; font-size:12pt">0</span><span style="font-family:微软雅黑; font-size:12pt">）日内协商不成的，任何一方均有权将该争议向</span><span style="font-family:微软雅黑; font-size:12pt">芜湖市经开区人民法院</span><span style="font-family:微软雅黑; font-size:12pt">提起诉讼。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、当产生任何争议及任何争议正按前条规定进行解决时，除争议事项外，双方应继续行使本协议项下的其他权利，履行本协议项下的其他义务。如本协议中的任何条款被认定为全部或部分不合法、无效或不可强制执行，并不影响其他条款的有效和执行。</span><span style="-aw-bookmark-end:_Hlk16090149"></span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt">
				<a name="_Hlk16090184"><span style="font-family:微软雅黑; font-size:12pt; font-weight:bold">十一、其他</span></a>
			</p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">1、本协议自受让方根据《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的规则对</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">转让进行签收同意之日起成立并生效。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">2、本协议未尽之事宜，如《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》已有约定的，适用《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》的约定。如《</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格会员服务协议</span><span style="font-family:微软雅黑; font-size:12pt">》没有约定的，由双方另行协商并签订补充协议解决，另行签订的补充协议与本协议具有同等法律效力。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">3、双方应秉承诚实信用之原则，采取一切必要的行为以确保本协议之生效及获完全执行，并避免采取任何与本协议条款不一致的行为。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">4、除非本协议另有约定，本协议生效后，任何一方不得单方面变更或解除本协议；对本协议的任何修改或变更必须经协议各方协商一致，并达成书面协议。</span></p>
			<p style="margin:0pt 0pt 10pt; text-align:justify; text-indent:24pt"><span style="font-family:微软雅黑; font-size:12pt">5、本协议及其修改或补充均采用通过</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台以电子文本形式制成，可以有一份或者多份并且每一份具有同等法律效力，并保存在</span><span style="font-family:微软雅黑; font-size:12pt">东风金融-创格</span><span style="font-family:微软雅黑; font-size:12pt">平台为此设立的专用服务器上备查和保管。双方均认可该形式的协议效力。</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="-aw-bookmark-end:_Hlk16090184"></span><span style="font-family:Calibri; font-size:10.5pt">&#xa0;</span></p>
		</div>
</template>
